apiVersion: v1
kind: Secret
metadata:
  name: weather-secrets
  namespace: weather-app
type: Opaque
stringData:
  POSTGRES_PASSWORD: password
  KEYCLOAK_DB_PASSWORD: keycloak
  KEYCLOAK_ADMIN_PASSWORD: admin
  REDIS_PASSWORD: ""
  WEATHER_DB_PASSWORD: weather_pass