apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-service
  namespace: weather-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-service
  template:
    metadata:
      labels:
        app: alert-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: [ 'sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done' ]
        - name: wait-for-kafka
          image: busybox
          command: [ 'sh', '-c', 'until nc -z kafka 9092; do echo waiting for kafka; sleep 2; done' ]
      containers:
        - name: alert-service
          image: alert-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            initialDelaySeconds: 45
            periodSeconds: 10