spring:
  data:
    redis:
      host: redis
      port: 6379
  cloud:
    discovery:
      enabled: false
    gateway:
      routes:
        - id: weather-service
          uri: http://weather-service:8082
          predicates:
            - Path=/api/weather/**
          filters:
            - name: CircuitBreaker
              args:
                name: weatherCB
                fallbackUri: forward:/fallback/weather
        - id: alert-service
          uri: http://alert-service:8083
          predicates:
            - Path=/api/alerts/**
          filters:
            - name: CircuitBreaker
              args:
                name: alertCB
                fallbackUri: forward:/fallback/alert
server:
  port: 8081
logging:
  level:
    org.springframework.cloud.gateway: INFO
    io.github.resilience4j: INFO