spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cloud:
    discovery:
      enabled: false
    gateway:
      routes:
        - id: weather-service-forecast
          uri: http://weather-service:8082
          predicates:
            - Path=/api/weather/forecast/**
        - id: weather-service-stream
          uri: http://${WEATHER_SERVICE_HOST:localhost}:${WEATHER_SERVICE_PORT:8082}
          predicates:
            - Path=/api/weather/stream/**
        - id: weather-service
          uri: http://${WEATHER_SERVICE_HOST:localhost}:${WEATHER_SERVICE_PORT:8082}
          predicates:
            - Path=/api/weather/**
          filters:
            - name: CircuitBreaker
              args:
                name: weatherCB
                fallbackUri: forward:/fallback/weather
        - id: alert-service
          uri: http://${ALERT_SERVICE_HOST:localhost}:${ALERT_SERVICE_PORT:8083}
          predicates:
            - Path=/api/alerts/**
          filters:
            - name: CircuitBreaker
              args:
                name: alertCB
                fallbackUri: forward:/fallback/alert
server:
  port: ${GATEWAY_PORT:8081}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
resilience4j:
  timelimiter:
    instances:
      weatherCB:
        timeoutDuration: 10s
      alertCB:
        timeoutDuration: 10s
  circuitbreaker:
    instances:
      weatherCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimumNumberOfCalls: 5
      alertCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimumNumberOfCalls: 5
logging:
  level:
    org.springframework.cloud.gateway: INFO
    io.github.resilience4j: INFO
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"